name: Release Project

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile project
        run: |
          make rebuild

      - name: Prepare source zip
        run: |
          zip -r parchis-source.zip . -x "obj/*" ".git/*" ".github/*"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Entrega Final - Proyecto 2"
          body: |
            Esta es la entrega del Simulador de Parchis. 
            - parchis-source.zip: Codigo fuente (usar `make rebuild && run`).
            - parchis: Ejecutable compilado para Linux.
          files: |
            parchis-source.zip
            parchis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}